import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/ThemeProvider.jsx";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { AuthProvider } from "../contexts/AuthProvider";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
     <html lang="en" className="font-chirp" suppressHydrationWarning>
      <body>
           <AuthProvider>
            <ThemeProvider defaultTheme="light" storageKey="elafda-ui-theme">
              <div className="relative flex min-h-screen flex-col">
                <Header />
                <main className="flex-1">{children}</main>
                <Footer />
              </div>
            </ThemeProvider>
            </AuthProvider>
               <Toaster richColors position="top-center" />
        
      </body>
    </html>
  );
}
